[package]
name = "prestino"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlparser = "0.18"
http = "0.2"
http-serde = "1.1"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }